version: 2.1

jobs:
  linting:
    docker:
      - image: cimg/node:22.11.0  # Use a Node.js Docker image
    working_directory: ~/repo  # Set the working directory to the root where your 'repo' is checked out

    steps:
      - checkout  # This step pulls your repository into ~/repo

      # Step 1: Install dependencies
      - run:
          name: Install Dependencies
          command: |
            cd ~/repo  # Ensure we are in the correct directory
            npm install  # Install npm dependencies

      # Step 2: Run ESLint
      - run:
          name: Run Linter
          command: |
            cd ~/repo  # Navigate to the project root (adjust if necessary)
            npm run lint  # Run ESLint to check for code issues

  testing:
    docker:
      - image: cimg/node:22.11.0  # Use a Node.js Docker image
    working_directory: ~/repo  # Set the working directory to the root where your 'repo' is checked out

    steps:
      - checkout  # This step pulls your repository into ~/repo

      # Step 1: Install dependencies
      - run:
          name: Install Dependencies
          command: |
            cd ~/repo  # Ensure we are in the correct directory
            npm install  # Install npm dependencies

      # Step 2: Run Tests
      - run:
          name: Run Tests
          command: |
            cd ~/repo  # Navigate to the project root (adjust if necessary)
            npm test  # Run Jest tests
    docker_push:
    docker:
      - image: cimg/docker:24.0  # Use a Docker image for building and pushing
    steps:
      - checkout  # Pull your repository

      # Step 1: Build Docker Image
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/your-image-name:latest .

      # Step 2: Login to Docker Hub
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Step 3: Push Docker Image
      - run:
          name: Push Docker Image
          command: |
            docker push your-dockerhub-username/your-image-name:latest
            
  deploy:
    docker:
      - image: cimg/node:22.11.0  # Use a Node.js Docker image
    working_directory: ~/repo  # Set the working directory to the root where your 'repo' is checked out

    steps:
      - checkout  # This step pulls your repository into ~/repo

      # Step 1: Deploy Application (Placeholder)
      - run:
          name: Deploy Application
          command: |
            echo "Deployment step will be implemented here"  # Placeholder for deployment

workflows:
  version: 2
  build_and_test:
    jobs:
      - linting
      - testing
      - deploy:
          requires:
            - testing
